AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.1


Style/ConstantVisibility:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Enabled: true
  Max: 120

Lint/ConstantResolution:
  Enabled: false

Metrics/MethodLength:
  Max: 15